services:
  - type: web
    name: my-flask-app
    env: python
    region: oregon
    buildCommand: |
      pip uninstall -y keras tensorflow transformers torch || true
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
